# PyTorch Tensor Basic Usage

- Create Tensor
- Indexing,Joining,Slicing
- Initialization
- Math Operations

(텐서 관련 자료)

https://wikidocs.net/57168

https://wikidocs.net/52460

https://wikidocs.net/52846


(자연어처리, 텐플)

https://wikidocs.net/21690  




## 1. Create Tensor
### 1) random numbers

In [ ]:
import torch

In [ ]:
x = torch.rand(2,3,4) # 0~1 균일분포
x

tensor([[[0.1025, 0.8879, 0.8156, 0.2509],
         [0.7138, 0.2956, 0.7769, 0.6836],
         [0.6277, 0.7832, 0.8781, 0.8522]],

        [[0.7216, 0.1937, 0.8386, 0.6073],
         [0.5408, 0.4271, 0.9040, 0.3615],
         [0.9653, 0.5945, 0.1413, 0.2290]]])

In [ ]:
x = torch.randn(2,3) # 평균 0, 표준편차 1의 가우시안 표준정규분포
x

tensor([[-0.1334,  0.0161,  0.3407],
        [-0.7423,  1.8771,  1.1009]])

In [ ]:
x = torch.randperm(6) # 정수난수
x

tensor([4, 0, 1, 3, 5, 2])

### 2) zeros, ones, arange

In [ ]:
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### 3) Tensor Data Type

In [ ]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

tensor([[1.3211e+16, 3.0743e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor([2,3]) #초기값을 [2,3] 리스트로 만들어서 넣어줌
x

tensor([2., 3.])

In [ ]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor()) # 앞서 정의한 x 텐서를 정수형으로 타입 변환한 것
x

tensor([2, 3], dtype=torch.int32)

### 4) Numpy to Tensor, Tensor to Numpy

In [ ]:
import numpy as np  #넘파이 -> 텐서, 텐서 -> 넘파이는 빈번하게 사용됨

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))

x2 = torch.from_numpy(x1) #########

x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# tensor.numpy() -> ndarray
x3 = x2.numpy() #########
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 5) Tensor on CPU & GPU

In [ ]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [ ]:
# pytorch 사용하면서 주로 발생하는 문제에서 해결하는 방법 
# 대부분 딥러닝 연산은 GPU에서 발생
# GPU에서 연산되던 어떤 레이어를 새로만든 텐서와 연산하려면 
#같은 GPU에 올려주거나 혹은 CPU로 가져와서 연산해야함

x_cpu = x_gpu.cpu()  
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 6) Tensor Size

In [ ]:
# tensor.size() -> indexing also possible
# 입력받은 데이터나, 새로만든 레이어, 필터 등을 검증할때(제대로 입력된 것 맞나..) 많이 사용함

x = torch.FloatTensor(10,12,3,3)

print(x)

x.size()[:]

tensor([[[[9.2293e+15, 3.0743e-41, 3.0912e+12],
          [3.0743e-41, 5.7397e-42, 0.0000e+00],
          [       nan,        nan, 4.3607e+27]],

         [[4.5448e+30, 0.0000e+00, 0.0000e+00],
          [6.6410e+05, 6.9785e+22, 7.5551e+31],
          [7.2251e+28, 2.8231e+23, 1.0645e+24]],

         [[1.8935e+23, 7.2076e+31, 1.8891e+31],
          [4.7418e+30, 7.1440e+31, 7.5876e+31],
          [2.0592e-10, 2.7264e+20, 3.0820e+32]],

         ...,

         [[1.9432e-19, 1.7260e+25, 1.6928e+22],
          [8.4503e+02, 4.3036e+21, 7.1848e+22],
          [7.8501e-33, 2.7509e+12, 1.8936e+23]],

         [[2.0026e-19, 6.7120e+22, 1.9435e-19],
          [1.2123e+25, 4.6114e+24, 1.7388e+25],
          [1.6040e+02, 8.9012e+05, 5.5231e+31]],

         [[1.4608e-19, 7.7140e+31, 2.8701e+32],
          [1.9346e-19, 4.6168e+24, 1.7564e+25],
          [7.5244e+28, 2.8530e+20, 8.3969e-33]]],


        [[[9.8439e-12, 9.8439e-12, 9.8439e-12],
          [9.8439e-12, 9.8439e-12, 9.8439e-12],
          [

torch.Size([10, 12, 3, 3])

## 2. Indexing, Slicing, Joining
### 1) Indexing

In [ ]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

x,out

(tensor([[0.0460, 0.4419, 0.5983],
         [0.4402, 0.6590, 0.2722],
         [0.9777, 0.6751, 0.7359],
         [0.0536, 0.6354, 0.6158]]), tensor([[0.0460, 0.4419, 0.5983],
         [0.0536, 0.6354, 0.6158]]))

In [ ]:
# pythonic indexing also works

x[:,0],x[0,:],x[0:2,0:2]

(tensor([0.0460, 0.4402, 0.9777, 0.0536]),
 tensor([0.0460, 0.4419, 0.5983]),
 tensor([[0.0460, 0.4419],
         [0.4402, 0.6590]]))

In [ ]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1356.)
  """


(tensor([[ 0.2993, -0.7145,  0.3851],
         [-0.2304,  0.0936,  1.4184]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([0.3851, 0.0936]))

### 2) Joining

In [27]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim
## 많이 사용함 (레이어 두개 붙일때)

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2


#[[1., 2., 3.],    [4., 5., 6.]   ] 
#[[-1., -2., -3.], [-4., -5., -6.]]
#[[ 1.,  2.,  3.], [ 4.,  5.,  6.],  [-1., -2., -3.],  [-4., -5., -6.]]
#[[ 1.,  2.,  3., -1., -2., -3.], [ 4.,  5.,  6., -4., -5., -6.]]

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [28]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### 3) Slicing

In [29]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks
# chunk는 데이터를 chunk개로 나눔 

x_1, x_2 = torch.chunk(z1,2,dim=0) #0번 차원에서 2개로 나누기
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1) #1번 차원에서 3개로 나누기

print(z1)
print(x_1)
print(x_2)

print(z1)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [ ]:
# torch.split(tensor,split_size,dim=0) -> split into specific size
# split의 경우 한 묶음 안에 split_size개가 생김 

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

z1,x1,x2,y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]), tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

### 4) squeezing

In [ ]:
# torch.squeeze(input,dim=None) -> reduce dim by 1
#1의 차원을 날림 (종종쓰임)

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [ ]:
# torch.unsqueeze(input,dim=None) -> add dim by 1
#1의 차원을 추가해줌 (종종쓰임)
x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 3. Initialization

In [ ]:
import torch.nn.init as init
#torch.nn.init에는 tensor에 초깃값을 주기 위해 필요한 함수들이 저장

x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9) 
#x 변수에 [3,4] 모양의 tensor을 생성하고 이 텐서의 값들을 init.uniform_() 함수를 통해서 
#0부터 9까지 uniform(균등) 하게 초기화

x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
#N(mean, std^2)을 따르는 정규 분포에서의 값을 input tensor에 집어넣어 준다.
#매개변수로는
#- Tensor : n 차원의 Tensor 크기를 집어넣어 준다. 그럼 그 크기만큼 만들어진다.
#예를 들어 torch.Tensor(3,5)를 집어넣으면 이차원인 3 * 5만큼의 정규 분포의 값이 만들어진다.
#- mean : 정규 분포에서의 평균 값
#- std : 정규 분포에서의 표준편차


x3 = init.constant(torch.FloatTensor(3,4),3.1415)
# 상수 값으로 초기화

x1,x2,x3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[2.0694, 1.8690, 5.0992, 5.4225],
         [8.9213, 8.5498, 3.5514, 6.9614],
         [0.0459, 6.7698, 6.7890, 1.0139]]),
 tensor([[-0.0251, -0.0527, -0.0710,  0.1183],
         [ 0.0807, -0.2969, -0.1759,  0.0809],
         [-0.0258, -0.2568,  0.1032, -0.0227]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

## 4. Math Operations
### 1) Arithmetic operations

In [ ]:
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [ ]:
# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

x1,x2,x1+10,x2-10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [ ]:
# torch.mul() -> size better match
# 행렬곱 아님!! 원소별 곱셈

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [ ]:
# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [ ]:
# torch.div() -> size better match
# 원소별 나눔
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) Other Math Operations

In [ ]:
# torch.pow(input,exponent)

x1 = torch.FloatTensor(3,4)
x1

tensor([[1.3211e+16, 3.0743e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.pow(x1,2),x1**2

(tensor([[   inf, 0.0000, 0.3600, 0.6400],
         [1.0000, 1.4400, 0.0000, 7.2227],
         [0.0000, 7.3916, 0.0000, 7.5625]]),
 tensor([[   inf, 0.0000, 0.3600, 0.6400],
         [1.0000, 1.4400, 0.0000, 7.2227],
         [0.0000, 7.3916, 0.0000, 7.5625]]))

In [ ]:
# torch.exp(tensor,out=None) 

x1 = torch.FloatTensor(3,4)
torch.exp(x1)

tensor([[0.0000e+00, 1.0000e+00, 1.4333e+00, 1.8965e+00],
        [2.7183e+00, 4.2207e+00, 1.0000e+00, 1.3701e+03],
        [1.0000e+00, 1.6223e+03, 1.0000e+00, 1.9247e+03]])

In [ ]:
# torch.log(input, out=None) -> natural logarithm

x1 = torch.FloatTensor(3,4)
torch.log(x1)

tensor([[     nan, -93.2855, -86.6356,   0.3646],
        [  1.9772,   2.0003,   2.0232,   0.6575],
        [    -inf,   0.8967,     -inf,   0.9010]])

### 3) Matrix operations

In [ ]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[        inf, -5.0495e-14, -1.1538e-16, -1.1538e-16, -1.0384e-16],
        [-1.9252e+27,  2.2365e-40,  9.4505e-41,  1.1179e-40,  9.6398e-41],
        [-7.3998e+29,  4.9877e-38,  2.4588e-40,  2.7016e-40,  2.3722e-40]])

In [ ]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication
#배치로 행렬곱

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [ ]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.FloatTensor(3)
x2 = torch.FloatTensor(3)

torch.dot(x1,x2)

tensor(inf)

In [ ]:
# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)

x1,x1.t()

(tensor([[-1.6467e+27,  3.0663e-41,  1.1538e-16,  1.1538e-16],
         [ 1.0384e-16,  1.9252e+27,  2.2365e-40,  9.4505e-41],
         [ 1.1179e-40,  9.6398e-41,  7.3998e+29,  4.9877e-38]]),
 tensor([[-1.6467e+27,  1.0384e-16,  1.1179e-40],
         [ 3.0663e-41,  1.9252e+27,  9.6398e-41],
         [ 1.1538e-16,  2.2365e-40,  7.3998e+29],
         [ 1.1538e-16,  9.4505e-41,  4.9877e-38]]))

In [ ]:
# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)

#x1 오리지널 사이즈, transpose함수 불러서 사용, x1에 바로 적용
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [ ]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)
x1

tensor([[-1.6467e+27,  3.0663e-41,  2.3694e-38,  2.3694e-38],
        [ 4.4721e+21,  3.0104e+29,  7.1853e+22,  7.1901e+28],
        [ 6.2706e+22,  4.7428e+30,  3.9891e+24,  4.1996e+12],
        [ 7.5338e+28,  1.5975e-43,  0.0000e+00,  0.0000e+00]])

In [ ]:
torch.eig(x1,True)

torch.return_types.eig(eigenvalues=tensor([[ 2.8269e+24,  0.0000e+00],
        [ 3.0104e+29,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-1.6467e+27,  0.0000e+00]]), eigenvectors=tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  3.2003e-05],
        [ 2.3868e-07, -6.3346e-02, -8.3473e-07,  3.4804e-04],
        [-1.0000e+00, -9.9799e-01,  1.0000e+00, -1.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.4956e-06, -1.4642e-03]]))